# fly.toml app configuration file generated for portfolio-roohan on 2025-10-23T18:36:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-roohan'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
